### ISSUE TITLE
Absent labels are rendered as "undefined" instead of ignored

### ISSUE THREAD

**Issue by herebebeasties** [ericdrowell/ElGrapho#8]
I'd like to optionally label my nodes, but if the first (any?) node has a label then any other nodes without a label property set have their label rendered as "undefined".

There's a workaround for this, which is to set nodes which you don't want to have labels on as `label: ""` but that's a bit unexpected.

**Comment by ericdrowell** [comment]
I will fix this as well over the weekend.  Thanks!
